version: "3.9"
services:
  redis:
    image: redis:7
    restart: unless-stopped
    ports: ["6379:6379"]

  api:
    build: .
    environment:
      - REDIS_ADDR=redis:6379
      - PORT=8080
      - JWT_SECRET=supersecret
    depends_on:
      - redis
    ports: ["8080:8080"]
