version: "3.9"
services:
  redis:
    image: redis:7
    restart: unless-stopped
    ports: ["6379:6379"]
  
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: notes
      POSTGRES_USER: notesuser
      POSTGRES_PASSWORD: notespass
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notesuser -d notes"]
      interval: 5s
      retries: 10

  api:
    build: .
    environment:
      - REDIS_ADDR=redis:6379
      - PORT=8080
      - JWT_SECRET=supersecret
      - DB_DSN=postgres://notesuser:notespass@postgres:5432/notes?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    ports: ["8080:8080"]
