name: CI
on: [push, pull_request]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Vet & Test
        run: |
          go vet ./...
          go test ./... -v

      - name: Build Docker image
        run: docker build -t notes-service:${{ github.sha }} .
